# Generated by Django 4.2.11 on 2024-05-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ontime_deliver_order',
            field=models.IntegerField(default=0),
        ),
    ]
