# Generated by Django 4.2.11 on 2024-05-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_purchaseorder_ontime_deliver_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='ontime_deliver_order',
        ),
    ]
