# Generated by Django 4.2.11 on 2024-05-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_alter_performance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='Vendor',
            new_name='vendor',
        ),
    ]
